---
title: "NC_data_analysis"
author: "Alokesh Manna"
date: "2024-03-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Inspired with the script model performance water table depth
```{r}
#install.packages("devtools")
library(devtools)

#install_github("wbnicholson/BigVAR/BigVAR")
 #install.packages("BigVAR")
library("BigVAR")
library(palmerpenguins)
library(tidyverse)
library(ggplot2)
#install.packages("ggpmisc")
#library(ggpmisc,depen)
library("hydroGOF")
```


load NC data
```{r}
library("readxl")

NC_data_1988_2008=read_excel("/Users/alokesh.manna17gmail.com/NSF_internship_2023/raw_data/NC_data/NC_1988_2008.xlsx")
head(NC_data_1988_2008)
```
```{r}
leap_year_months=c(
  rep(1,31),
      rep(2,29),
      rep(3,31),
      rep(4,30),
      rep(5,31),
      rep(6,30),
      rep(7,31),
      rep(8,31),
      rep(9,30),
      rep(10,31),
      rep(11,30),
      rep(12,31))


nonleap_year_months=c(
  rep(1,31),
      rep(2,28),
      rep(3,31),
      rep(4,30),
      rep(5,31),
      rep(6,30),
      rep(7,31),
      rep(8,31),
      rep(9,30),
      rep(10,31),
      rep(11,30),
      rep(12,31))


is_leap_year <- function(year) {
  if ((year %% 4 == 0 && year %% 100 != 0) || year %% 400 == 0) {
    return(1)
  } else {
    return(0)
  }
}


```

```{r}
tail(NC_data_1988_2008)


```

```{r}
year=c(1988:2008)
leap_year_evaluation=sapply(1:length(year),function(i){is_leap_year(year[i])})
  
mon=NULL

for(j in 1:length(year)){
  if(leap_year_evaluation[j]==1){
    mon=append(mon,leap_year_months)
  }else{
    mon=append(mon,nonleap_year_months)
  }
  
}


NC_data_1988_2008=NC_data_1988_2008|>mutate(month_extracted=mon)

```


```{r}
COEF_NC=NULL
preformance_test_depth_NC=NULL
preformance_train_depth_NC=NULL
```




```{r}
Y_NC=NC_data_1988_2008%>%drop_na%>%select(c(Depth_cm_b,Air_Temp_C,Rainfall,DailyFlow,Solar_rad_,net_rad,PET,RH,Windspeed_,Vapor_Kpa))
VARX=list()
VARX$k=1 # indicates that the first two series are modeled
VARX$m=11
VARX$s=2 # sets 2 as the maximal lag order for exogenous series
Model1_NC=constructModel(data.matrix(Y_NC),p=4,struct='BasicEN',gran=c(500,10),verbose=FALSE,VARX=VARX,T1=floor(nrow(Y_NC)/3),T2=floor(2*nrow(Y_NC)/3))

results=cv.BigVAR(Model1_NC)
#results
#plot(results)
#SparsityPlot.BigVAR.results(results)
#predict(results,n.ahead=1, confint=TRUE)
#coef(results)
COEF_NC=COEF_NC%>%bind_rows(coef(results))
```




```{r}
dim(Y_NC)
length(results@fitted)##You must get p differences as the traning starts p step ahead from begining. 
length(results@preds)
length(results@resids)
sum((results@resids))
#length(results@preds)+length(results@resids)
#dim(as.matrix(Y_77%>%drop_na()))
#sum(resids)
#c(results@fitted[1:T1],results@fitted[(T2+1):nrow(Y)])
results@preds[1360]
results@fitted[4076] ##This two values are same confirming the fact that in fitted we have the prediction values in last length(results@preds)=1360 values.
```
##Already NA is dropped.

```{r,,fig.width=2,fig.height=2}
Y=Y_NC%>%select("Depth_cm_b")%>%as.matrix()
X=Y_NC%>%select(-c("Depth_cm_b"))%>%as.matrix()
#T1=floor(nrow(Y)/3)
#T2=floor(2*nrow(Y)/3)
#X <- matrix(0,nrow=nrow(Y),ncol=ncol(Y))
#BICMSFE <- VARXForecastEval(Y,X,p=4,s=2,T1,T2,"BIC",1)##****This part gives the error.
#length(BICMSFE$pred)
#y=tail(Y,length(BICMSFE$pred))


x=results@preds
y=tail(Y,length(x))
mon=NC_data_1988_2008%>%drop_na%>%select("month_extracted")
mon=tail(mon$month_extracted,length(x))

#c(results@fitted[1:T1],results@fitted[(T2+1):nrow(Y)]) 

preformance_test_depth_NC=preformance_test_depth_NC%>%bind_rows("daily"=data.frame(gof(y, x)))

pic=data.frame(y,x,mon)%>%mutate(Month=as.factor(mon))
ggplot(pic,aes(x,y))+
  geom_point(alpha=.3)+
  geom_point(aes(colour=Month)) +
  scale_fill_manual(values =c(pic$Month))+
  geom_abline()+
  coord_fixed() +
  xlab("predicted")+
  ylab("act")+
  ylim(-1,3)+
  xlim(-1,3)+
  #ggtitle('water table depth y=x, in cm, daily ws77 recent_time')+
theme(plot.title = element_text(size = 10, face = "bold"),legend.spacing.y = unit(.001, 'cm'),legend.spacing.x = unit(.001, 'cm'),legend.position='bottom',legend.key.size =  unit(.03, 'cm'))

ggsave(file="water table depth y=x, in cm, daily wsNC_recent_time.png", device = "png",path="pictures_new_well_depth_recent_time")
```
```{r}
NC_data_1988_2008
```




```{r}
NC_data_1988_2008=NC_data_1988_2008|>
  mutate(T=1:n())|>
  mutate(dt=as.Date(T, origin = '1987-12-31'))

date=  tail(NC_data_1988_2008%>%
              #drop_na%>%
              select(c("T")),length(x))$T
      
dt= tail(NC_data_1988_2008%>%
           #drop_na%>%
           select(c("dt")),length(x))$dt

dat=data.frame(date,predicted= -100*x, actual= -100*y[,1])##as we want it in meter and negative to be comparable

mean_cl_quantile <- function(x, q = c(0.1, 0.9), na.rm = TRUE){
  dat <- data.frame(y = mean(x, na.rm = na.rm),
                    ymin = quantile(x, probs = q[1], na.rm = na.rm),
                    ymax = quantile(x, probs = q[2], na.rm = na.rm))
  return(dat)
}

ggplot(dat,aes(dt))+
  #coord_fixed() +
  geom_point(aes(y=predicted, colour = "predicted"),pch=20) + 
  geom_point(aes(y=actual, colour = "actual"),pch=20)+
  xlab("Date")+
  ylab("water table depth")+
  ylim(-250,100)+
  #xlim(-1,3)+
  #labs(color = Legend)+
  ggtitle('water table depth time series prediction recent time for daily ws NC')+
  #geom_smooth(stat = 'summary', fun.data = mean_cl_quantile(x))+
  theme_minimal()+
theme(axis.title = element_text(size = 25),
      plot.title = element_text(size = 25, face = "plain"),
      legend.spacing.y = unit(0, 'cm'),
      legend.spacing.x = unit(0, 'cm'),
      legend.position=c(0.5,0.1),
      legend.key.size =  unit(.15, 'cm'),
      axis.line = element_line(color='black'),
      plot.background = element_blank(),
      panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank()
    )
  
ggsave(file="depth in m prediction ts plot recent time, daily wsNC", device = "png",path="pictures_new_well_depth_recent_time")

```



```{r}
pic =bind_cols(y,x,mon)%>%mutate(Month=as.factor(mon))%>%ggplot(aes(x = -100*x, y = -100*y,color=Month)) +
  scale_fill_manual(values = c(mon))+
  geom_point() +
  geom_abline()+
  coord_fixed() +
  xlab("predicted")+
  ylab("act")+
  xlim(-300,100)+
  ylim(-300,100)+
  theme_bw()+
  ggtitle("water table depth, cm, monthly-facet-daily wsNC")+
  theme(plot.title = element_text(size = 8, face = "plain"),
        axis.line = element_line(color='black'),
      plot.background = element_blank(),
      panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank())
 pic+ facet_wrap(~Month)

ggsave(file="water table depth, cm, monthly-facet-daily wsNC_recent_time.png.png", device = "png",path="pictures_new_well_depth_recent_time") 
```



```{r,fig.width=1.6,fig.height=1.6}

ggplot( data = dat,aes(x=predicted,y=actual)) +
  #stat_poly_line()+
  #stat_poly_eq(use_label(c("eq","adj.R2", "f", "p")),size = 1.6) +
  xlab("predicted")+
  ylab("act")+
  xlim(-300,100)+
  ylim(-300,100)+
 
  
  #ggtitle("water table depth, in cm, daily ws80_recent_time.png")+
  geom_point()+
  theme(plot.title = element_text(size = 8, face = "bold"))
ggsave(file="water table depth, in cm, daily ws80_recent_time.png.png", device = "png",path="pictures_new_well_depth_recent_time")
```



```{r}
library(ggplot2)

#create residual plot with title and axis labels
ggplot(data = data.frame(x,y), aes(x = -100*x, y = -100*(y-x))) +
  geom_point() +
  geom_hline(yintercept = 0) +
  geom_smooth(se = FALSE)+
  labs(x='Fitted Values', y='Residuals')+
  ggtitle("water table depth residuals, cm, monthly-facet-daily wsNC")+
  theme_bw()+
  theme(plot.title = element_text(size = 14, face = "plain"),
        axis.line = element_line(color='black'),
      plot.background = element_blank(),
      panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank())
ggsave(file="Residual analysis, water table depth, in cm, daily wsNC_recent_time.png.png", device = "png",path="pictures_new_well_depth_recent_time")
```






```{r}
hist(NC_data_1988_2008|>pull(Depth_cm_b)*(-100),breaks=200,prob=T)
```

```{r}
SparsityPlot.BigVAR.results(results)
#Air_Temp_C,Rainfall,DailyFlow,Solar_rad_,net_rad,PET,RH,Windspeed_,Vapor_Kpa
```
```{r}
datNC=dat
```

```{r}
# mean_cl_quantile <- function(x, q = c(0.1, 0.9), na.rm = TRUE){
#   dat <- data.frame(y = mean(x, na.rm = na.rm),
#                     ymin = quantile(x, probs = q[1], na.rm = na.rm),
#                     ymax = quantile(x, probs = q[2], na.rm = na.rm))
#   return(dat)
# }

newdat=datNC



sd=sd(dat$predicted-dat$actual)
  
newdat$lower=datNC$predicted-3*sd
newdat$upper=datNC$predicted+3*sd

ggplot(newdat,aes(dt, predicted)) +
  geom_point(aes(y=predicted, colour = "predicted"),pch=2) + 
  geom_point(aes(y=actual, colour = "actual"),pch=4)+
  xlab("Date")+
  ylab("water table depth")+
  ylim(-250,100)+
  #xlim(-1,3)+
  #labs(color = Legend)+
  ggtitle('water table depth time series prediction recent time for daily ws NC')+
  #geom_smooth(stat = 'summary', fun.data = mean_cl_quantile(x))+
  geom_ribbon(aes(ymin = lower, ymax = upper, fill = "Confidence Interval"), alpha = 0.4)+
  theme_minimal()+
theme(axis.title = element_text(size = 25), 
      plot.title = element_text(size = 18, face = "plain"),
      legend.spacing.y = unit(0, 'cm'),
      legend.spacing.x = unit(0, 'cm'),
      legend.position=c(0.1,0.9),
      legend.key.size =  unit(.15, 'cm'),
      axis.line = element_line(color='black'),
      plot.background = element_blank(),
      panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank()
    )
  
  #stat_summary(geom = "line", fun = mean) +
  #stat_summary(geom = "ribbon", fun.data = mean_cl_quantile, alpha = 0.3)

```
datNC dry year 2007
```{r}
newdat=datNC|>
  mutate(date=dt)|>filter(date<"2008-01-01")|>filter(date>"2006-12-31")

sd=sd(datNC$predicted-datNC$actual)
  
newdat$lower=newdat$predicted-3*sd
newdat$upper=newdat$predicted+3*sd

# date_df=data.frame(date=NC_data_1988_2008%>%
#                      dplyr::select(c("dt"))|>
#                      filter(dt>=newdat$date[1])|>
#                      pull(dt)|>
#                      c())

ggplot(
  
         #date_df|>
         #left_join(newdat)|>
  newdat|>
         filter(date<"2008-01-01")|>
         filter(date>"2006-12-31"),aes(date, predicted)) +
#ggplot(newdat,aes(date, predicted)) +
  geom_point(aes(y=predicted, colour = "predicted"),pch=2) + 
  geom_point(aes(y=actual, colour = "actual"),pch=4)+
  xlab("Date")+
  ylab("water table depth")+
  ylim(-250,100)+
  #xlim(-1,3)+
  #labs(color = Legend)+
  ggtitle('water table depth daily level prediction for dry season 2007 D1 in NC')+
  #geom_smooth(stat = 'summary', fun.data = mean_cl_quantile(x))+
  geom_ribbon(aes(ymin = lower, ymax = upper, fill = "Confidence Interval"), alpha = 0.4)+
  theme_minimal()+
theme(axis.title = element_text(size = 25), 
      plot.title = element_text(size = 18, face = "plain"),
      legend.spacing.y = unit(0, 'cm'),
      legend.spacing.x = unit(0, 'cm'),
      legend.position=c(0.1,0.9),
      legend.key.size =  unit(.15, 'cm'),
      axis.line = element_line(color='black'),
      plot.background = element_blank(),
      panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank()
    )
  
  #stat_summary(geom = "line", fun = mean) +
  #stat_summary(geom = "ribbon", fun.data = mean_cl_quantile, alpha = 0.3)

```


datNC wet year 2005
```{r}
newdat=datNC|>
  mutate(date=dt)|>filter(date<"2006-01-01")|>filter(date>"2004-12-31")

sd=sd(datNC$predicted-datNC$actual)
  
newdat$lower=newdat$predicted-3*sd
newdat$upper=newdat$predicted+3*sd

# date_df=data.frame(date=NC_data_1988_2008%>%
#                      dplyr::select(c("dt"))|>
#                      filter(dt>=newdat$date[1])|>
#                      pull(dt)|>
#                      c())

ggplot(
  
         #date_df|>
         #left_join(newdat)|>
  newdat|>
         filter(date<"2006-01-01")|>
         filter(date>"2004-12-31"),aes(date, predicted)) +
#ggplot(newdat,aes(date, predicted)) +
  geom_point(aes(y=predicted, colour = "predicted"),pch=2) + 
  geom_point(aes(y=actual, colour = "actual"),pch=4)+
  xlab("Date")+
  ylab("water table depth")+
  ylim(-250,100)+
  #xlim(-1,3)+
  #labs(color = Legend)+
  ggtitle('water table depth daily level prediction for wet season 2005 D1 in NC')+
  #geom_smooth(stat = 'summary', fun.data = mean_cl_quantile(x))+
  geom_ribbon(aes(ymin = lower, ymax = upper, fill = "Confidence Interval"), alpha = 0.4)+
  theme_minimal()+
theme(axis.title = element_text(size = 25), 
      plot.title = element_text(size = 18, face = "plain"),
      legend.spacing.y = unit(0, 'cm'),
      legend.spacing.x = unit(0, 'cm'),
      legend.position=c(0.1,0.9),
      legend.key.size =  unit(.15, 'cm'),
      axis.line = element_line(color='black'),
      plot.background = element_blank(),
      panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank()
    )
  
  #stat_summary(geom = "line", fun = mean) +
  #stat_summary(geom = "ribbon", fun.data = mean_cl_quantile, alpha = 0.3)

```


```{r}
gof(dat$predicted,dat$actual)
```

```{r}
mod_nc_daily=lm(dat$actual~dat$predicted)
```

```{r}
summary(mod_nc_daily)
```

A wet year plot
```{r}

newdat=dat78|>filter(date<"2017-01-01")|>filter(date>"2015-12-31")

sd=sd(dat78$predicted-dat78$actual)
  
newdat$lower=newdat$predicted-3*sd
newdat$upper=newdat$predicted+3*sd

date_df=data.frame(date=dat_ws78_2006_2019%>%
                     dplyr::select(c("Date_"))|>
                     filter(Date_>=newdat$date[1])|>
                     pull(Date_)|>
                     c())

ggplot(date_df|>
         left_join(newdat)|>
         filter(date<"2017-01-01")|>
         filter(date>"2015-12-31"),aes(date, predicted)) +
#ggplot(newdat,aes(date, predicted)) +
  geom_point(aes(y=predicted, colour = "predicted"),pch=2) + 
  geom_point(aes(y=actual, colour = "actual"),pch=4)+
  xlab("Date")+
  ylab("water table depth")+
  ylim(-250,100)+
  #xlim(-1,3)+
  #labs(color = Legend)+
  ggtitle('water table depth time series prediction recent time for daily ws 78')+
  #geom_smooth(stat = 'summary', fun.data = mean_cl_quantile(x))+
  geom_ribbon(aes(ymin = lower, ymax = upper, fill = "Confidence Interval"), alpha = 0.4)+
  theme_minimal()+
theme(axis.title = element_text(size = 25), 
      plot.title = element_text(size = 18, face = "plain"),
      legend.spacing.y = unit(0, 'cm'),
      legend.spacing.x = unit(0, 'cm'),
      legend.position=c(0.5,0.1),
      legend.key.size =  unit(.15, 'cm'),
      axis.line = element_line(color='black'),
      plot.background = element_blank(),
      panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank()
    )
  
  #stat_summary(geom = "line", fun = mean) +
  #stat_summary(geom = "ribbon", fun.data = mean_cl_quantile, alpha = 0.3)

```

